### ISSUE TITLE
Partial send of parameters to test rig

### ISSUE THREAD

**Issue by TanDro** [umit-iace/tool-pywisp#39]

**Comment by TanDro** [comment]
@gruberth You find in 0a33ed53cb25e9a22169897862ba255e385af2eb a first version of partial module send. Please can you check and verifiy?

**Comment by gruberth** [comment]
I have used 0a33ed5 today and the last days when I was working on the bench. Everything works fine, but i have not especially checked if the parameters are send or recieved partial.

**Comment by gruberth** [comment]
As mentioned last time, it would be nice if the partial send is able to handle the reset value from an remote pushbutton.
For example when I want to run a trajectory I am sending a `1` to the testbench with a pushbutton. The Flag resets itself in the settingslist to the reset Value `0` after the `1` got send (without sending the `0`). When I press the pushbutton again to restart the trajectory, obviously nothing happens because the last sended parameter was `1`.
Is there a possibility to use the settingslist as reference for last changed parameters?

**Comment by TanDro** [comment]
I have included a solution in a43add375c45db6e342bd6beeb348e8f151072fa
